name: 'Run in docker'
description: 'Run command in docker'

inputs:
  command:
    description: 'Command to run'
    default: ''

  baseImage:
    description: 'Image to use'
    default: 'centos7'

  target:
    description: 'Target to run'
    default: 'builder'

  docker_elevation_argument:
    description: 'Command to add elevation (if needed)'
    default: ''

runs:
  using: "composite"
  steps:
    - name: Build on ${{ inputs.baseImage }} Docker image
      shell: bash
      run: |
        ${{ inputs.docker_elevation_argument }} docker build \
          --build-arg DOTNETSDK_VERSION=8.0.100 \
          --tag dd-trace-dotnet/${{ inputs.baseImage }}-${{ inputs.target }} \
          --target ${{ inputs.target }} \
          --file "${GITHUB_WORKSPACE}/tracer/build/_build/docker/${{ inputs.baseImage }}.dockerfile" \
          "${GITHUB_WORKSPACE}/tracer/build/_build"

    - name: Run '${{ inputs.command }}' in Docker
      shell: bash
      run: |
        ${{ inputs.docker_elevation_argument }} docker run --rm \
            --mount type=bind,source="${GITHUB_WORKSPACE}",target=/project \
            --env NugetPackageDirectory=/project/packages \
            --env tracerHome=/project/shared/bin/monitoring-home/tracer \
            --env artifacts=/project/tracer/src/bin/artifacts \
            --env DD_CLR_ENABLE_NGEN=1 \
            --env Verify_DisableClipboard=true \
            --env DiffEngine_Disabled=true \
            --env TestAllPackageVersions=false \
            --env IncludeMinorPackageVersions=false \
            --env NUGET_ENABLE_EXPERIMENTAL_HTTP_RETRY=true \
            dd-trace-dotnet/${{ inputs.baseImage }}-${{ inputs.target }} \
            dotnet /build/bin/Debug/_build.dll ${{ inputs.command }}