name: Build

on:
  pull_request:
  workflow_dispatch:

env:
  target: builder
  baseImage: debian

jobs:
  build:
    runs-on: arm-4core-linux

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '8.0.100'

      - name: Install docker
        run: |
          curl -fsSL https://get.docker.com -o get-docker.sh
          sudo sh get-docker.sh

      - name: Build and run debian Docker image - build
        uses: ./.github/actions/run-in-docker
        with:
          baseImage: ${{ env.baseImage }}
          target: builder
          docker_elevation_argument: sudo
          command: 'Clean BuildTracerHome BuildNativeLoader ExtractDebugInfoLinux'

      - name: Build and run debian Docker image - test
        uses: ./.github/actions/run-in-docker
        with:
          baseImage: ${{ env.baseImage }}
          target: tester
          docker_elevation_argument: sudo
          apiKey: ${{ secrets.DD_API_KEY }}
          command: 'BuildAndRunManagedUnitTests'
